# Generated by Django 6.1.1 on 2026-10-03 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва кафедри')),
                ('head', models.CharField(max_length=255, verbose_name='Завідувач кафедри')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва спеціальності')),
                ('code', models.CharField(max_length=50, verbose_name='Код спеціальності')),
                ('description', models.TextField(verbose_name='Повний опис')),
                ('coordinator_name', models.CharField(max_length=255, verbose_name='Імʼя координатора')),
                ('coordinator_contact', models.CharField(max_length=255, verbose_name='Контакт координатора')),
                ('disciplines', models.TextField(verbose_name='Список дисциплін')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='law_faculty.department', verbose_name='Випускова кафедра')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Імʼя викладача')),
                ('position', models.CharField(max_length=255, verbose_name='Посада')),
                ('degree', models.CharField(max_length=255, verbose_name='Науковий ступінь')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='law_faculty.department', verbose_name='Кафедра')),
            ],
        ),
    ]
