# Generated by Django 6.1.1 on 2026-10-03 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва спеціальності')),
                ('code', models.CharField(max_length=50, verbose_name='Код спеціальності')),
                ('description', models.TextField(verbose_name='Повний опис')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='law_faculty.department', verbose_name='Випускова кафедра')),
            ],
        ),
    ]
