# Generated by Django 6.1.1 on 2026-10-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_faculty', '0002_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='coordinator_contacts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт координатора набору'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='coordinator_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я координатора набору"),
        ),
        migrations.AddField(
            model_name='specialty',
            name='disciplines',
            field=models.TextField(blank=True, null=True, verbose_name='Список дисциплін'),
        ),
    ]
