# Generated by Django 6.1.1 on 2026-10-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_faculty', '0003_specialty_coordinator_contacts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255, verbose_name='Університет')),
                ('languages', models.CharField(max_length=255, verbose_name='Мови навчання')),
                ('slots', models.CharField(max_length=50, verbose_name='Кількість місць')),
                ('deadline', models.DateField(verbose_name='Дедлайн подачі')),
                ('description', models.TextField(verbose_name='Опис')),
            ],
        ),
    ]
