# Generated by Django 6.1.1 on 2026-10-05 19:37

from django.db import migrations, models

def split_university_and_country(apps, schema_editor):
    ExchangeProgram = apps.get_model('law_faculty', 'ExchangeProgram')
    for prog in ExchangeProgram.objects.all():
        raw = prog.university
        if '(' in raw and ')' in raw:
            parts = raw.split('(')
            prog.university = parts[0].strip()
            prog.country = parts[1].replace(')', '').strip()
        elif ',' in raw:
            parts = raw.rsplit(',', 1)
            prog.university = parts[0].strip()
            prog.country = parts[1].strip()
        elif '-' in raw:
            parts = raw.rsplit('-', 1)
            prog.university = parts[0].strip()
            prog.country = parts[1].strip()
        prog.save()

def reverse_split(apps, schema_editor):
    ExchangeProgram = apps.get_model('law_faculty', 'ExchangeProgram')
    for prog in ExchangeProgram.objects.all():
        if prog.country:
            prog.university = f"{prog.university}, {prog.country}"
            prog.save()

class Migration(migrations.Migration):

    dependencies = [
        ('law_faculty', '0004_exchangeprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprogram',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Країна'),
        ),
        migrations.RunPython(split_university_and_country, reverse_split),
    ]
