# Generated by Django 6.1.1 on 2026-10-05 19:44

from django.db import migrations, models
import re

def convert_slots_to_int(apps, schema_editor):
    ExchangeProgram = apps.get_model('law_faculty', 'ExchangeProgram')
    for prog in ExchangeProgram.objects.all():
        raw_slots = str(prog.slots)
        # Шукаєм перше ліпше число в рядку
        numbers = re.findall(r'\d+', raw_slots)
        if numbers:
            prog.slots = int(numbers[0])
        else:
            prog.slots = 1 # Значення за замовчуванням, якщо число не знайдено
        prog.save()

def reverse_slots_to_str(apps, schema_editor):
    ExchangeProgram = apps.get_model('law_faculty', 'ExchangeProgram')
    for prog in ExchangeProgram.objects.all():
        prog.slots = str(prog.slots)
        prog.save()

class Migration(migrations.Migration):

    dependencies = [
        ('law_faculty', '0005_exchangeprogram_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeprogram',
            name='slots',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість місць'),
        ),
        migrations.RunPython(convert_slots_to_int, reverse_slots_to_str),
    ]
