# Generated by Django 6.1.1 on 2026-10-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law_faculty', '0006_auto_20261005_2244'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            INSERT INTO law_faculty_exchangeprogram (university, country, languages, slots, deadline, description) VALUES
            ('Uniwersytet Warszawski', 'Польща', 'польська, англійська', '5', '2026-11-15', 'Один із провідних класичних університетів Польщі з багатими академічними традиціями та широким спектром програм обміну.'),
            ('KU Leuven', 'Бельгія', 'English', '2 місця', '2026-12-01', 'Найстаріший католицький університет Європи, відомий високим рівнем наукових досліджень та якісною освітою.'),
            ('Vilnius University', 'Литва', 'англійська', 'до 4', '2026-10-20', 'Найстаріший університет Литви та Балтійського регіону з сучасними європейськими підходами до навчання.'),
            ('Uniwersytet Jagielloński', 'Польща', 'Польська, Англійська', '3', '2026-11-15', 'Історичний польський університет у Кракові, який пропонує чудові можливості для академічного зростання студентів.'),
            ('University of Tartu', 'Естонія', 'англійська, естонська', '2', '2027-01-10', 'Провідний дослідницький центр Естонії та один із найкращих університетів Східної Європи.'),
            ('Masaryk University', 'Чехія', 'англійська', '1 місце', '2026-09-30', 'Сучасний чеський університет у Брно, що забезпечує динамічне середовище для міжнародних студентів.');
            """,
            reverse_sql="""
            DELETE FROM law_faculty_exchangeprogram WHERE university IN (
                'Uniwersytet Warszawski',
                'KU Leuven',
                'Vilnius University',
                'Uniwersytet Jagielloński',
                'University of Tartu',
                'Masaryk University'
            );
            """
        ),
    ]
