# Generated by Django 6.1.1 on 2026-10-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_faculty', '0006_auto_20261005_2244'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
        INSERT INTO law_faculty_exchangeprogram (university, languages, seats, deadline, description) VALUES
        ('Uniwersytet Warszawski, Польща', 'польська, англійська', '5', '2026-11-15', 'Польський університет з високими стандартами європейської освіти.'),
        ('KU Leuven (Бельгія)', 'English', '2 місця', '2026-12-01', 'Провідний дослідницький університет Бельгії.'),
        ('Vilnius University, Литва', 'англійська', 'до 4', '2026-10-20', 'Найстаріший університет Литви з багатими академічними традиціями.'),
        ('Uniwersytet Jagielloński, Польща', 'Польська, Англійська', '3', '2026-11-15', 'Один з найстаріших та найпрестижніших вузів Центральної Європи.'),
        ('University of Tartu - Естонія', 'англійська, естонська', '2', '2027-01-10', 'Провідний центр наукових досліджень Естонії.'),
        ('Masaryk University, Чехія', 'англійська', '1 місце', '2026-09-30', 'Сучасний європейський університет у місті Брно.');
        """,
        reverse_sql="DELETE FROM law_faculty_exchangeprogram;"
            ),
    ]
