# Generated by Django 6.1.1 on 2026-10-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_faculty', '0007_auto_20261006_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeprogram',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='languages',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='slots',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='university',
            field=models.CharField(max_length=200),
        ),
    ]
